export { default as Email } from './Email'
export { default as Facebook } from './Facebook'
export { default as Google } from './Google'
export { default as Password } from './Password'
export { default as Phone } from './Phone'
export { default as Twitter } from './Twitter'
