export { default as Help } from './Placeholder'
export { default as Payment } from './Placeholder'
export { default as Promos } from './Placeholder'
export { default as Profile } from './Profile'
export { default as Rides } from './Rides'
export { default as Settings } from './Placeholder'
export { default as Dashboard } from './Dashboard'
export { default as Contact } from './Contact'
