export const GET_DRIVERS = 'GET_DRIVERS'
export const GET_LOCATION = 'GET_LOCATION'
export const ERROR = 'ERROR'
export const SET_DESTINATION = 'SET_DESTINATION'
export const SET_PICKUP = 'SET_PICKUP'
